"""Tests for the demo page, /metrics and /demo/scenarios.

The HTML is not the risk here. The risk is that adding routes breaks the one endpoint that
gates everything, or that the page becomes a G5 liability by putting a URL on screen in
front of a judge. Both are tested explicitly.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from app.cache import Cache
from app.main import app
from backend.matcher.catalog import contains_url

KIT_PATH = Path(__file__).resolve().parents[1] / "student_kit" / "siis_responses.json"


@pytest.fixture
def client():
    with TestClient(app) as test_client:
        yield test_client


# ------------------------------------------------------------------ G2 is sacred -----


def test_health_is_untouched_by_the_new_routes(client):
    """The reason this test exists at all.

    Adding a route at "/" is exactly the moment a catch-all can shadow /health, and G2 is an
    exact-match check whose failure zeroes all 60 automated points and skips every live
    check. Asserted again here rather than trusting that it still works.
    """
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {"status": "ok"}


def test_health_body_has_no_extra_keys(client):
    """A build marker or uptime field here would fail an exact-match gate. It lives on
    /metrics for precisely this reason."""
    assert list(client.get("/health").json()) == ["status"]


def test_troubleshoot_still_works_with_the_new_routes(client):
    from app.validator import validate

    response = client.post(
        "/v1/troubleshoot",
        json={
            "query": "my screen is black",
            "siis_response": {
                "title": "Blank display",
                "content": "## Force a Restart\nPress and hold the Power button.",
            },
        },
    )
    assert response.status_code == 200
    assert validate(response.json())["ok"] is True


# ---------------------------------------------------------------- the demo page -----


def test_root_serves_html(client):
    response = client.get("/")
    assert response.status_code == 200
    assert response.headers["content-type"].startswith("text/html")
    assert "<!doctype html>" in response.text.lower()
    assert "Bixel" in response.text


def test_page_loads_nothing_from_another_origin(client):
    """Deliberate: no CDN, no npm, no build step.

    A demo that fails because a CDN is slow during judging is worse than a plain one, and a
    cross-origin script would also be blocked in an offline container.
    """
    text = client.get("/").text
    assert "script src=" not in text
    assert "//cdn" not in text
    assert "https://" not in text.replace("bixby://", "")


def test_page_only_calls_its_own_origin(client):
    """The service sends no CORS headers, so the page must use relative paths only."""
    text = client.get("/").text
    for path in ('fetch("/v1/troubleshoot"', 'fetch("/metrics")', 'fetch("/demo/scenarios")'):
        assert path in text, f"missing same-origin call: {path}"


def test_page_is_honest_about_the_masked_deeplinks(client):
    """The catalog URIs are Samsung's masked placeholders. A judge who spots a faked Bixby
    launch stops trusting anything else on the page."""
    text = client.get("/").text
    assert "masked" in text
    assert "never generated by the model" in text


# ------------------------------------------------------------------ scenarios -----


def test_scenarios_covers_the_kit_and_the_unseen_set(client):
    scenarios = client.get("/demo/scenarios").json()["scenarios"]
    assert len(scenarios) == 28, "expected 20 kit rows + 8 unseen payloads"
    groups = {s["group"] for s in scenarios}
    assert groups == {"Samsung kit (graded)", "Unseen (generalization)"}
    assert sum(1 for s in scenarios if s["group"] == "Samsung kit (graded)") == 20
    assert sum(1 for s in scenarios if s["group"] == "Unseen (generalization)") == 8


@pytest.mark.parametrize("row_id", ["row_3", "row_11", "row_17"])
def test_the_samsung_com_rows_are_sanitized_before_reaching_the_browser(client, row_id):
    """These three contain kidshome.pin@samsung.com in their content.

    Served raw, the page would display a live URL in front of a judge -- making this
    endpoint a G5 liability even though the graded /v1/troubleshoot path is clean.
    """
    scenarios = client.get("/demo/scenarios").json()["scenarios"]
    row = next(s for s in scenarios if s["id"] == row_id)
    assert not contains_url(json.dumps(row)), "URL survived into the scenario payload"
    assert "samsung.com" not in json.dumps(row)


def test_no_scenario_anywhere_leaks_a_url(client):
    payload = client.get("/demo/scenarios").json()
    offenders = [s["id"] for s in payload["scenarios"] if contains_url(json.dumps(s))]
    assert offenders == []


def test_every_scenario_is_directly_submittable(client):
    """The page posts these straight back, so each needs a query and both SIIS fields."""
    for scenario in client.get("/demo/scenarios").json()["scenarios"]:
        assert scenario["query"].strip(), scenario["id"]
        assert scenario["siis_response"]["title"].strip(), scenario["id"]
        assert scenario["siis_response"]["content"].strip(), scenario["id"]


def test_scenario_documents_keep_the_line_structure_of_the_kit(client):
    """Regression guard for a bug that silently degraded every demo request.

    This endpoint used to run documents through ``sanitize()``, which collapses all
    whitespace. That is right for single-line output strings and destructive for a document:
    the character count barely moves while every newline becomes a space. Since
    ``build_candidates()`` splits on ``##`` headings and line breaks, row_12's document went
    from 6 candidate sections to 1, and its catalog deeplink from 7-of-8 uncached runs to
    0-of-3. The demo page was the only caller, so the graded path never showed it -- which is
    exactly why it needs a test rather than a comment.

    Asserting line counts match the kit byte-for-byte would be wrong: sanitising row_3, row_11
    and row_17 removes an address and can empty a line. Line *count* is the invariant that
    matters to the parser, so that is what is asserted.
    """
    kit = {
        row["id"]: row["siis_response"]["content"]
        for row in json.loads(KIT_PATH.read_text(encoding="utf-8"))["responses"]
    }
    served = {
        s["id"]: s["siis_response"]["content"]
        for s in client.get("/demo/scenarios").json()["scenarios"]
    }

    mismatched = {
        row_id: (len(raw.splitlines()), len(served[row_id].splitlines()))
        for row_id, raw in kit.items()
        if len(raw.splitlines()) != len(served[row_id].splitlines())
    }
    assert mismatched == {}, f"line structure lost for {mismatched}"

    multiline = [rid for rid, raw in kit.items() if len(raw.splitlines()) > 1]
    assert multiline, "kit documents are multi-line; this guard is meaningless otherwise"
    assert all("\n" in served[rid] for rid in multiline)


# -------------------------------------------------------------------- metrics -----


def test_metrics_has_the_documented_shape(client):
    metrics = client.get("/metrics").json()
    assert set(metrics) == {
        "cache", "requests", "latency_ms", "cost_usd", "build", "model_chain",
    }
    assert set(metrics["cache"]) == {
        "hits", "misses", "hit_rate", "buckets", "entries", "similarity_threshold",
    }
    assert set(metrics["latency_ms"]) == {"p50", "p95", "last"}


def test_metrics_survives_a_cold_cache(client):
    """Zero hits and zero misses must not divide by zero, and must not claim 0%.

    "No requests yet" and "every request missed" are different facts; reporting 0% for the
    first would be a dashboard that lies.
    """
    metrics = client.get("/metrics").json()
    assert metrics["cache"]["hit_rate"] is None or isinstance(metrics["cache"]["hit_rate"], float)
    if metrics["requests"] == 0:
        assert metrics["latency_ms"]["p95"] is None


def test_cost_is_honestly_zero(client):
    """Not marketing: the matcher, the cache and the deterministic fallback cost nothing,
    and only an uncached request pays a Gemini call."""
    assert client.get("/metrics").json()["cost_usd"] == 0.0


def test_metrics_reports_the_build_marker(client):
    """Answers "what is actually deployed?", which was unanswerable before."""
    assert client.get("/metrics").json()["build"]


def test_metrics_counts_real_requests(client):
    before = client.get("/metrics").json()["requests"]
    payload = {
        "query": "my screen is black",
        "siis_response": {
            "title": "Blank display",
            "content": "## Force a Restart\nPress and hold the Power button.",
        },
    }
    client.post("/v1/troubleshoot", json=payload)
    after = client.get("/metrics").json()
    assert after["requests"] == before + 1
    assert after["latency_ms"]["last"] is not None


def test_metrics_reports_the_live_model_chain(client):
    from backend.extract.client import MODEL_CHAIN

    assert client.get("/metrics").json()["model_chain"] == list(MODEL_CHAIN)


# ------------------------------------------------------------- cache.stats() -----


def test_cache_stats_on_a_cold_cache():
    stats = Cache().stats()
    assert stats["hits"] == 0 and stats["misses"] == 0
    assert stats["hit_rate"] is None, "a cold cache has no rate, and 0.0 would be a lie"
    assert stats["buckets"] == 0 and stats["entries"] == 0


def test_cache_stats_tracks_hits_and_misses():
    cache = Cache()
    siis = {"title": "t", "content": "## H\nTap Settings."}
    query = "my Galaxy S22 screen is completely black and will not turn on"
    cache.get_or_compute(query, siis, lambda: "x")
    cache.get_or_compute(query, siis, lambda: "y")
    stats = cache.stats()
    assert (stats["hits"], stats["misses"]) == (1, 1)
    assert stats["hit_rate"] == 0.5
    assert stats["entries"] == 1


def test_cache_stats_is_read_only():
    """The dashboard must be able to observe the cache without being able to change it."""
    cache = Cache()
    cache.get_or_compute("q", {"title": "t", "content": "c"}, lambda: "x")
    snapshot = cache.stats()
    snapshot["hits"] = 999
    assert cache.stats()["hits"] == 0
